name: Basement
author: ohAlee
version: 2.1.0
main: it.hemerald.basementx.bukkit.BasementPluginMain
api-version: 1.17
depend: [LuckPerms]
softdepend: [Vulcan, PlaceholderAPI, SkinsRestorer, Vault]
commands:
  basementx:
    aliases: [basement]
    permission: basement.staff
  tabreload:
    permission: basement.reloadtab
  staffmode:
    permission: basement.staff
    aliases:
      - staff
      - smode
  vanish:
    permission: basement.staff
  cheatban:
    permission: cheat.ban
  streammode:
    aliases: [sm]

permissions:
  basement.staff:
    default: op
  basement.reloadtab:
    default: op
  cheat.ban:
    default: op