name: Basement
author: TheDarkSword
version: ${pluginVersion}
main: it.hemerald.basementx.bukkit.BasementPluginMain
api-version: 1.17
depend: [LuckPerms]
softdepend: [Vulcan, PlaceholderAPI, SkinsRestorer, Vault]
commands:
  basementx:
    aliases: [basement]
    permission: basement.staff
  tabreload:
    permission: basement.reloadtab
  staffmode:
    permission: basement.staff
    aliases:
      - staff
      - sf
      - smode
      - staffm
  vanish:
    permission: basement.staff
#  tag:
#    aliases: [tags, nametag, nametags]
  cheatban:
    permission: cheat.ban
  streammode:
    aliases: [sm]
  bedwars:
  thebridge:
    aliases: [bridge, bg]

permissions:
  basement.staff:
    default: op
  basement.reloadtab:
    default: op
  cheat.ban:
    default: op