name: Basement
author: TheDarkSword
version: ${pluginVersion}
main: it.hemerald.basementx.bukkit.BasementPluginMain
api-version: 1.17
depend: [LuckPerms, ViaVersion]
softdepend: [Vulcan, PlaceholderAPI, SkinsRestorer]
commands:
  basementx:
    aliases: [basement]
    permission: hemerald.staff
  tabreload:
    permission: hemerald.reloadtab
  staffmode:
    permission: hemerald.staff
    aliases:
      - staff
      - sf
      - smode
      - staffm
  vanish:
    permission: hemerald.staff
  tag:
    aliases: [tags, nametag, nametags]
  cheatban:
    permission: cheat.ban

permissions:
  hemerald.staff:
    default: op
  hemerald.reloadtab:
    default: op
  cheat.ban:
    default: op